INSERT INTO CONTACT (ID, NAME) VALUES (1, 'Aaron');
INSERT INTO CONTACT (ID, NAME) VALUES (2, 'Benjamin');
INSERT INTO CONTACT (ID, NAME) VALUES (3, 'Michael');
INSERT INTO CONTACT (ID, NAME) VALUES (4, 'John');
INSERT INTO CONTACT (ID, NAME) VALUES (5, 'Agata');